CREATE SCHEMA marketfy;
USE marketfy;
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE marketfy.USERS (
	user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50),
    bio VARCHAR(200),
    email VARCHAR(200) NOT NULL,
    password VARCHAR(200) NOT NULL,
    areas_of_interest VARCHAR(300)
);


-- CREATE A DEFAULT USER

INSERT INTO marketfy.USERS (first_name, last_name, bio, email, password, areas_of_interest)
VALUES("Leonardo", "Madrigal", "Software Developer", "Leonardo@Madrigal.com", "123", "Software,Animals,Sport");

-- OTHER TESTING COMMANDS
-- UPDATE marketfy.USERS SET areas_of_interest = "Software, Animals, Sport" WHERE user_id = 1;
-- DELETE FROM marketfy.USERS WHERE user_id=2;
-- SELECT * FROM marketfy.USERS;
-- DROP TABLE marketfy.USERS;

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE marketfy.PRODUCTS(
	product_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR (100) NOT NULL,
    price FLOAT NOT NULL,
    image LONGBLOB,
    description VARCHAR(500),
    total_in_inventory INT NOT NULL
);

-- ADD DEFAULT PRODUCTS

INSERT INTO marketfy.PRODUCTS(title,price, description, total_in_inventory, image) VALUES ('Product 1', 3.33, 'Description of product 1', 333, 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (2,'Classic Red Pullover Hoodie',10,'Elevate your casual wardrobe with our Classic Red Pullover Hoodie. Crafted with a soft cotton blend for ultimate comfort, this vibrant red hoodie features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs for a snug fit. The timeless design ensures easy pairing with jeans or joggers for a relaxed yet stylish look, making it a versatile addition to your everyday attire.','https://i.imgur.com/1twoaDy.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (3,'Classic Heather Gray Hoodie',69,'Stay cozy and stylish with our Classic Heather Gray Hoodie. Crafted from soft, durable fabric, it features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs. Perfect for a casual day out or a relaxing evening in, this hoodie is a versatile addition to any wardrobe.','https://i.imgur.com/cHddUCu.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (4,'Classic Grey Hooded Sweatshirt',90,'Elevate your casual wear with our Classic Grey Hooded Sweatshirt. Made from a soft cotton blend, this hoodie features a front kangaroo pocket, an adjustable drawstring hood, and ribbed cuffs for a snug fit. Perfect for those chilly evenings or lazy weekends, it pairs effortlessly with your favorite jeans or joggers.','https://i.imgur.com/R2PN9Wq.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (5,'Classic Black Hooded Sweatshirt',79,'Elevate your casual wardrobe with our Classic Black Hooded Sweatshirt. Made from high-quality, soft fabric that ensures comfort and durability, this hoodie features a spacious kangaroo pocket and an adjustable drawstring hood. Its versatile design makes it perfect for a relaxed day at home or a casual outing.','https://i.imgur.com/cSytoSD.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (6,'Classic Comfort Fit Joggers',25,'Discover the perfect blend of style and comfort with our Classic Comfort Fit Joggers. These versatile black joggers feature a soft elastic waistband with an adjustable drawstring, two side pockets, and ribbed ankle cuffs for a secure fit. Made from a lightweight and durable fabric, they are ideal for both active days and relaxed lounging.','https://i.imgur.com/ZKGofuB.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (7,'Classic Comfort Drawstring Joggers',79,'Experience the perfect blend of comfort and style with our Classic Comfort Drawstring Joggers. Designed for a relaxed fit, these joggers feature a soft, stretchable fabric, convenient side pockets, and an adjustable drawstring waist with elegant gold-tipped detailing. Ideal for lounging or running errands, these pants will quickly become your go-to for effortless, casual wear.','https://i.imgur.com/mp3rUty.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (8,'Classic Red Jogger Sweatpants',98,'Experience ultimate comfort with our red jogger sweatpants, perfect for both workout sessions and lounging around the house. Made with soft, durable fabric, these joggers feature a snug waistband, adjustable drawstring, and practical side pockets for functionality. Their tapered design and elastic cuffs offer a modern fit that keeps you looking stylish on the go.','https://i.imgur.com/9LFjwpI.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (9,'Classic Navy Blue Baseball Cap',61,'Step out in style with this sleek navy blue baseball cap. Crafted from durable material, it features a smooth, structured design and an adjustable strap for the perfect fit. Protect your eyes from the sun and complement your casual looks with this versatile and timeless accessory.','https://i.imgur.com/R3iobJA.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (10,'Classic Blue Baseball Cap',86,'Top off your casual look with our Classic Blue Baseball Cap, made from high-quality materials for lasting comfort. Featuring a timeless six-panel design with a pre-curved visor, this adjustable cap offers both style and practicality for everyday wear.','https://i.imgur.com/wXuQ7bm.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (13,'Classic Olive Chino Shorts',84,'Elevate your casual wardrobe with these classic olive chino shorts. Designed for comfort and versatility, they feature a smooth waistband, practical pockets, and a tailored fit that makes them perfect for both relaxed weekends and smart-casual occasions. The durable fabric ensures they hold up throughout your daily activities while maintaining a stylish look.','https://i.imgur.com/UsFIvYs.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (14,'Classic High-Waisted Athletic Shorts',43,'Stay comfortable and stylish with our Classic High-Waisted Athletic Shorts. Designed for optimal movement and versatility, these shorts are a must-have for your workout wardrobe. Featuring a figure-flattering high waist, breathable fabric, and a secure fit that ensures they stay in place during any activity, these shorts are perfect for the gym, running, or even just casual wear.','https://i.imgur.com/eGOUveI.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (15,'Classic White Crew Neck T-Shirt',39,'Elevate your basics with this versatile white crew neck tee. Made from a soft, breathable cotton blend, it offers both comfort and durability. Its sleek, timeless design ensures it pairs well with virtually any outfit. Ideal for layering or wearing on its own, this t-shirt is a must-have staple for every wardrobe.','https://i.imgur.com/axsyGpD.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (16,'Classic White Tee - Timeless Style and Comfort',73,'Elevate your everyday wardrobe with our Classic White Tee. Crafted from premium soft cotton material, this versatile t-shirt combines comfort with durability, perfect for daily wear. Featuring a relaxed, unisex fit that flatters every body type, it''s a staple piece for any casual ensemble. Easy to care for and machine washable, this white tee retains its shape and softness wash after wash. Pair it with your favorite jeans or layer it under a jacket for a smart look.','https://i.imgur.com/Y54Bt8J.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (17,'Classic Black T-Shirt',35,'Elevate your everyday style with our Classic Black T-Shirt. This staple piece is crafted from soft, breathable cotton for all-day comfort. Its versatile design features a classic crew neck and short sleeves, making it perfect for layering or wearing on its own. Durable and easy to care for, it''s sure to become a favorite in your wardrobe.','https://i.imgur.com/9DqEOV5.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (18,'Sleek White & Orange Wireless Gaming Controller',69,'Elevate your gaming experience with this state-of-the-art wireless controller, featuring a crisp white base with vibrant orange accents. Designed for precision play, the ergonomic shape and responsive buttons provide maximum comfort and control for endless hours of gameplay. Compatible with multiple gaming platforms, this controller is a must-have for any serious gamer looking to enhance their setup.','https://i.imgur.com/ZANVnHE.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (19,'Sleek Wireless Headphone & Inked Earbud Set',44,'Experience the fusion of style and sound with this sophisticated audio set featuring a pair of sleek, white wireless headphones offering crystal-clear sound quality and over-ear comfort. The set also includes a set of durable earbuds, perfect for an on-the-go lifestyle. Elevate your music enjoyment with this versatile duo, designed to cater to all your listening needs.','https://i.imgur.com/yVeIeDa.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (20,'Sleek Comfort-Fit Over-Ear Headphones',28,'Experience superior sound quality with our Sleek Comfort-Fit Over-Ear Headphones, designed for prolonged use with cushioned ear cups and an adjustable, padded headband. Ideal for immersive listening, whether you''re at home, in the office, or on the move. Their durable construction and timeless design provide both aesthetically pleasing looks and long-lasting performance.','https://i.imgur.com/SolkFEB.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (21,'Efficient 2-Slice Toaster',48,'Enhance your morning routine with our sleek 2-slice toaster, featuring adjustable browning controls and a removable crumb tray for easy cleaning. This compact and stylish appliance is perfect for any kitchen, ensuring your toast is always golden brown and delicious.','https://i.imgur.com/keVCVIa.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (22,'Sleek Wireless Computer Mouse',10,'Experience smooth and precise navigation with this modern wireless mouse, featuring a glossy finish and a comfortable ergonomic design. Its responsive tracking and easy-to-use interface make it the perfect accessory for any desktop or laptop setup. The stylish blue hue adds a splash of color to your workspace, while its compact size ensures it fits neatly in your bag for on-the-go productivity.','https://i.imgur.com/w3Y8NwQ.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (23,'Sleek Modern Laptop with Ambient Lighting',43,'Experience next-level computing with our ultra-slim laptop, featuring a stunning display illuminated by ambient lighting. This high-performance machine is perfect for both work and play, delivering powerful processing in a sleek, portable design. The vibrant colors add a touch of personality to your tech collection, making it as stylish as it is functional.','https://i.imgur.com/OKn1KFI.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (24,'Sleek Modern Laptop for Professionals',97,'Experience cutting-edge technology and elegant design with our latest laptop model. Perfect for professionals on-the-go, this high-performance laptop boasts a powerful processor, ample storage, and a long-lasting battery life, all encased in a lightweight, slim frame for ultimate portability. Shop now to elevate your work and play.','https://i.imgur.com/ItHcq7o.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (25,'Stylish Red & Silver Over-Ear Headphones',39,'Immerse yourself in superior sound quality with these sleek red and silver over-ear headphones. Designed for comfort and style, the headphones feature cushioned ear cups, an adjustable padded headband, and a detachable red cable for easy storage and portability. Perfect for music lovers and audiophiles who value both appearance and audio fidelity.','https://i.imgur.com/YaSqa06.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (26,'Sleek Mirror Finish Phone Case',27,'Enhance your smartphone''s look with this ultra-sleek mirror finish phone case. Designed to offer style with protection, the case features a reflective surface that adds a touch of elegance while keeping your device safe from scratches and impacts. Perfect for those who love a minimalist and modern aesthetic.','https://i.imgur.com/yb9UQKL.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (27,'Sleek Smartwatch with Vibrant Display',16,'Experience modern timekeeping with our high-tech smartwatch, featuring a vivid touch screen display, customizable watch faces, and a comfortable blue silicone strap. This smartwatch keeps you connected with notifications and fitness tracking while showcasing exceptional style and versatility.','https://i.imgur.com/LGk9Jn2.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (28,'Sleek Modern Leather Sofa',53,'Enhance the elegance of your living space with our Sleek Modern Leather Sofa. Designed with a minimalist aesthetic, it features clean lines and a luxurious leather finish. The robust metal legs provide stability and support, while the plush cushions ensure comfort. Perfect for contemporary homes or office waiting areas, this sofa is a statement piece that combines style with practicality.','https://i.imgur.com/Qphac99.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (29,'Mid-Century Modern Wooden Dining Table',24,'Elevate your dining room with this sleek Mid-Century Modern dining table, featuring an elegant walnut finish and tapered legs for a timeless aesthetic. Its sturdy wood construction and minimalist design make it a versatile piece that fits with a variety of decor styles. Perfect for intimate dinners or as a stylish spot for your morning coffee.','https://i.imgur.com/DMQHGA0.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (30,'Elegant Golden-Base Stone Top Dining Table',66,'Elevate your dining space with this luxurious table, featuring a sturdy golden metal base with an intricate rod design that provides both stability and chic elegance. The smooth stone top in a sleek round shape offers a robust surface for your dining pleasure. Perfect for both everyday meals and special occasions, this table easily complements any modern or glam decor.','https://i.imgur.com/NWIJKUj.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (31,'Modern Elegance Teal Armchair',25,'Elevate your living space with this beautifully crafted armchair, featuring a sleek wooden frame that complements its vibrant teal upholstery. Ideal for adding a pop of color and contemporary style to any room, this chair provides both superb comfort and sophisticated design. Perfect for reading, relaxing, or creating a cozy conversation nook.','https://i.imgur.com/6wkyyIN.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (32,'Elegant Solid Wood Dining Table',67,'Enhance your dining space with this sleek, contemporary dining table, crafted from high-quality solid wood with a warm finish. Its sturdy construction and minimalist design make it a perfect addition for any home looking for a touch of elegance. Accommodates up to six guests comfortably and includes a striking fruit bowl centerpiece. The overhead lighting is not included.','https://i.imgur.com/4lTaHfF.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (33,'Modern Minimalist Workstation Setup',49,'Elevate your home office with our Modern Minimalist Workstation Setup, featuring a sleek wooden desk topped with an elegant computer, stylish adjustable wooden desk lamp, and complimentary accessories for a clean, productive workspace. This setup is perfect for professionals seeking a contemporary look that combines functionality with design.','https://i.imgur.com/3oXNBst.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (34,'Modern Ergonomic Office Chair',71,'Elevate your office space with this sleek and comfortable Modern Ergonomic Office Chair. Designed to provide optimal support throughout the workday, it features an adjustable height mechanism, smooth-rolling casters for easy mobility, and a cushioned seat for extended comfort. The clean lines and minimalist white design make it a versatile addition to any contemporary workspace.','https://i.imgur.com/3dU0m72.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (35,'Futuristic Holographic Soccer Cleats',39,'Step onto the field and stand out from the crowd with these eye-catching holographic soccer cleats. Designed for the modern player, these cleats feature a sleek silhouette, lightweight construction for maximum agility, and durable studs for optimal traction. The shimmering holographic finish reflects a rainbow of colors as you move, ensuring that you''ll be noticed for both your skills and style. Perfect for the fashion-forward athlete who wants to make a statement.','https://i.imgur.com/qNOjJje.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (36,'Rainbow Glitter High Heels',39,'Step into the spotlight with these eye-catching rainbow glitter high heels. Designed to dazzle, each shoe boasts a kaleidoscope of shimmering colors that catch and reflect light with every step. Perfect for special occasions or a night out, these stunners are sure to turn heads and elevate any ensemble.','https://i.imgur.com/62gGzeF.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (37,'Chic Summer Denim Espadrille Sandals',33,'Step into summer with style in our denim espadrille sandals. Featuring a braided jute sole for a classic touch and adjustable denim straps for a snug fit, these sandals offer both comfort and a fashionable edge. The easy slip-on design ensures convenience for beach days or casual outings.','https://i.imgur.com/9qrmE1b.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (38,'Vibrant Runners: Bold Orange & Blue Sneakers',27,'Step into style with these eye-catching sneakers featuring a striking combination of orange and blue hues. Designed for both comfort and fashion, these shoes come with flexible soles and cushioned insoles, perfect for active individuals who don''t compromise on style. The reflective silver accents add a touch of modernity, making them a standout accessory for your workout or casual wear.','https://i.imgur.com/hKcMNJs.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (39,'Vibrant Pink Classic Sneakers',84,'Step into style with our Vibrant Pink Classic Sneakers! These eye-catching shoes feature a bold pink hue with iconic white detailing, offering a sleek, timeless design. Constructed with durable materials and a comfortable fit, they are perfect for those seeking a pop of color in their everyday footwear. Grab a pair today and add some vibrancy to your step!','https://i.imgur.com/mcW42Gi.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (40,'Futuristic Silver and Gold High-Top Sneaker',68,'Step into the future with this eye-catching high-top sneaker, designed for those who dare to stand out. The sneaker features a sleek silver body with striking gold accents, offering a modern twist on classic footwear. Its high-top design provides support and style, making it the perfect addition to any avant-garde fashion collection. Grab a pair today and elevate your shoe game!','https://i.imgur.com/npLfCGq.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (41,'Futuristic Chic High-Heel Boots',36,'Elevate your style with our cutting-edge high-heel boots that blend bold design with avant-garde aesthetics. These boots feature a unique color-block heel, a sleek silhouette, and a versatile light grey finish that pairs easily with any cutting-edge outfit. Crafted for the fashion-forward individual, these boots are sure to make a statement.','https://i.imgur.com/HqYqLnW.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (42,'Elegant Patent Leather Peep-Toe Pumps with Gold-Tone Heel',53,'Step into sophistication with these chic peep-toe pumps, showcasing a lustrous patent leather finish and an eye-catching gold-tone block heel. The ornate buckle detail adds a touch of glamour, perfect for elevating your evening attire or complementing a polished daytime look.','https://i.imgur.com/AzAY4Ed.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (43,'Elegant Purple Leather Loafers',17,'Step into sophistication with our Elegant Purple Leather Loafers, perfect for making a bold statement. Crafted from high-quality leather with a vibrant purple finish, these shoes feature a classic loafer silhouette that''s been updated with a contemporary twist. The comfortable slip-on design and durable soles ensure both style and functionality for the modern man.','https://i.imgur.com/Au8J9sX.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (44,'Classic Blue Suede Casual Shoes',39,'Step into comfort with our Classic Blue Suede Casual Shoes, perfect for everyday wear. These shoes feature a stylish blue suede upper, durable rubber soles for superior traction, and classic lace-up fronts for a snug fit. The sleek design pairs well with both jeans and chinos, making them a versatile addition to any wardrobe.','https://i.imgur.com/sC0ztOB.jpeg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (45,'Sleek Futuristic Electric Bicycle',22,'This modern electric bicycle combines style and efficiency with its unique design and top-notch performance features. Equipped with a durable frame, enhanced battery life, and integrated tech capabilities, it''s perfect for the eco-conscious commuter looking to navigate the city with ease.','https://i.imgur.com/BG8J0Fj.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (46,'Sleek All-Terrain Go-Kart',37,'Experience the thrill of outdoor adventures with our Sleek All-Terrain Go-Kart, featuring a durable frame, comfortable racing seat, and robust, large-tread tires perfect for handling a variety of terrains. Designed for fun-seekers of all ages, this go-kart is an ideal choice for backyard racing or exploring local trails.','https://i.imgur.com/Ex5x3IU.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (47,'Radiant Citrus Eau de Parfum',73,'Indulge in the essence of summer with this vibrant citrus-scented Eau de Parfum. Encased in a sleek glass bottle with a bold orange cap, this fragrance embodies freshness and elegance. Perfect for daily wear, it''s an olfactory delight that leaves a lasting, zesty impression.','https://i.imgur.com/xPDwUb3.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (48,'Sleek Olive Green Hardshell Carry-On Luggage',48,'Travel in style with our durable hardshell carry-on, perfect for weekend getaways and business trips. This sleek olive green suitcase features smooth gliding wheels for easy airport navigation, a sturdy telescopic handle, and a secure zippered compartment to keep your belongings safe. Its compact size meets most airline overhead bin requirements, ensuring a hassle-free flying experience.','https://i.imgur.com/jVfoZnP.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (49,'Chic Transparent Fashion Handbag',61,'Elevate your style with our Chic Transparent Fashion Handbag, perfect for showcasing your essentials with a clear, modern edge. This trendy accessory features durable acrylic construction, luxe gold-tone hardware, and an elegant chain strap. Its compact size ensures you can carry your day-to-day items with ease and sophistication.','https://i.imgur.com/Lqaqz59.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (50,'Trendy Pink-Tinted Sunglasses',38,'Step up your style game with these fashionable black-framed, pink-tinted sunglasses. Perfect for making a statement while protecting your eyes from the glare. Their bold color and contemporary design make these shades a must-have accessory for any trendsetter looking to add a pop of color to their ensemble.','https://i.imgur.com/0qQBkxX.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (51,'Elegant Glass Tumbler Set',50,'Enhance your drinkware collection with our sophisticated set of glass tumblers, perfect for serving your favorite beverages. This versatile set includes both clear and subtly tinted glasses, lending a modern touch to any table setting. Crafted with quality materials, these durable tumblers are designed to withstand daily use while maintaining their elegant appeal.','https://i.imgur.com/TF0pXdL.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (1+100,'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',109.95,'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday','https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (1,'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',109.95,'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday','https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (2,'Mens Casual Premium Slim Fit T-Shirts',22.3,'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.','https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (3,'Mens Cotton Jacket',55.99,'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.','https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (4,'Mens Casual Slim Fit',15.99,'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.','https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (5,'John Hardy Women''s Legends Naga Gold & Silver Dragon Station Chain Bracelet',695,'From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean''s pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.','https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (6,'Solid Gold Petite Micropave',168,'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.','https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (7,'White Gold Plated Princess',9.99,'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine''s Day...','https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (8,'Pierced Owl Rose Gold Plated Stainless Steel Double',10.99,'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel','https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (9,'WD 2TB Elements Portable External Hard Drive - USB 3.0',64,'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system','https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (10,'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s',109,'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)','https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (11,'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5',109,'3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.','https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (12,'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive',114,'Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer''s limited warranty','https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (13,'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin',599,'21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz','https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (14,'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED',999.99,'49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag','https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (16,'Lock and Love Women''s Removable Hooded Faux Leather Moto Biker Jacket',29.95,'100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON','https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (17,'Rain Jacket Women Windbreaker Striped Climbing Raincoats',39.99,'Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn''t overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.','https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (18,'MBJ Women''s Solid Short Sleeve Boat Neck V',9.85,'95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem','https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (19,'Opna Women''s Short Sleeve Moisture',7.95,'100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort','https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg');
INSERT INTO marketfy.PRODUCTS(total_in_inventory,title,price,description,image) VALUES (20,'DANVOUY Womens T Shirt Casual Cotton Short',12.99,'95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.','https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg');

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE marketfy.USER_SELECTION(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    product_quantity INT NOT NULL,
    stored_in VARCHAR(8) NOT NULL
);

-- ADD DEFAULT VALUES TO WISHLIST
INSERT INTO marketfy.USER_SELECTION(user_id, product_id, product_quantity, stored_in) VALUES (1, 1, 1, "wishlist");
INSERT INTO marketfy.USER_SELECTION(user_id, product_id, product_quantity, stored_in) VALUES (1, 2, 2, "wishlist");
INSERT INTO marketfy.USER_SELECTION(user_id, product_id, product_quantity, stored_in) VALUES (1, 3, 3, "wishlist");

-- OTHER TESTING COMMANDS
-- SELECT * FROM marketfy.USER_SELECTION;
-- DROP TABLE marketfy.USER_SELECTION;
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE marketfy.ORDER_HISTORY(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    order_date DATE NOT NULL,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    product_price FLOAT NOT NULL,
    product_quantity INT NOT NULL,
	product_title VARCHAR (100) NOT NULL,
    product_image LONGBLOB
);

-- ADD DEFAULT VALUES TO ORDER HISTORY

INSERT INTO marketfy.ORDER_HISTORY (order_id, order_date, user_id, product_id, product_price, product_quantity, product_title, product_image) VALUES ('1', CURDATE(), 1, 1, 1, 1, "'Classic Red Pullover Hoodie'", 'https://i.imgur.com/1twoaDy.jpeg');
INSERT INTO marketfy.ORDER_HISTORY (order_id, order_date, user_id, product_id, product_price, product_quantity, product_title, product_image) VALUES ('1', CURDATE(), 1, 2, 3, 3, "'Classic Heather Gray Hoodie", 'https://i.imgur.com/cHddUCu.jpeg');
INSERT INTO marketfy.ORDER_HISTORY (order_id, order_date, user_id, product_id, product_price, product_quantity, product_title, product_image) VALUES ('2', CURDATE(), 1, 2, 3, 3, "'Classic Heather Gray Hoodie", 'https://i.imgur.com/cHddUCu.jpeg');

-- OTHER TESTING COMMANDS

-- SELECT * FROM marketfy.ORDER_HISTORY;
-- SELECT * FROM marketfy.ORDER_HISTORY 
-- WHERE user_id = 1 
-- AND order_id = 1;
-- DROP TABLE marketfy.ORDER_HISTORY;